# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "RustFest"
email: "noreply@nospam.com"
description: "Let's rust"
baseurl: ""
url: "http://www.rustfest.eu/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Rust Community Europe e.V."
organizerAlternateName: "RustEurope Foundation"
organizerDescription: ""
organizerEmail: "team"
organizerLogo: ""
organizerLink: "http://www.rustc.eu/"

# Head

metaKeywords: "event, rust, rustlang, berlin, conference"
twitterAccount: "@rustfest"
#socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "mailto:sponsors@rustfest.eu?subject=becoming%20a%20partner&body=Hello+Team+OpenSourceBash%2C%0D%0A%0D%0Awe+are+%0D%0A%0D%0Aand+we%27d+like+to+partner+with+you+for+the+event.+We+can+offer+%0D%0A%0D%0A%0D%0AThanks+for+getting+back+to+us"


# Navigation
navigationLinks:
 - {permalink: "/", text: "About"}
 # - {permalink: "/#presenting", text: "Presenting"}
 # - {permalink: "/#schedule", text: "Schedule"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/code-of-conduct/", text: "Code of Conduct"}
 - {permalink: "/accessibility/", text: "Accessibility"}
 - {permalink: "/#latest-news", text: "News"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "#tickets", text: "Register Now"}
rightNavigationButtons:
 # - {link: "/apply", cls: "btn-secondary", text: "Present Project"}
 - {link: "#tickets", text: "Register Now"}

# Hero Block
heroImage: "berlin_sunset.jpg"
heroTitle: "<typeout> Rust"
eventDate: "RustFest, Berlin, Sept 17th(-18th) 2016"
typeoutTextValues: '"", "talking", "learning", "improving", "hacking", "presenting"'
typeoutFallback: "talking about"
heroButtons:
 - {permalink: "/#tickets", text: "register now"}

# About Block
aboutTitle: "About RustFestEU"
# aboutText: "<p>Each presentation consist of 5 minutes, where three minutes focus on the project and the second two cover how to onboard easiest and fastest.</p><p>There will be three batches of five talks each and breaks in between at which participants can chat with the teams and learn more about the projects and how to get involved.</p>"
aboutBlock:
 - {title: "Presentations", image: "anouk_presents.png", text: "OpenSource teams present their project, what it is and why it matters to an audience of people interested in joining and contributing." }
 - {title: "Connect", image: "pandas.jpg", text: "Breaks and having great food together gives plenty of opportunity for participants to learn about the projects they are intersted in." }
 - {title: "Start Contributing", image: "kids_contributing.jpg", text: "All presentations are focussed on lowering the threshold of getting involved. After, you can chat with the teams. Bring your Laptop and set up the project together with the maintainers." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "attendees", detail: "interested in contributing, joining from everywhere in the world"}
 - {count: "15", specialCharacter: "", info: "open source teams✨", detail: "presenting their projects and show how you can join <strong>today</strong>"}
 - {count: "5", specialCharacter: "", info: "minutes each!", detail: "per presentation – 3min about the projects, 2min on how to contribute. "}
 # - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Presenting"
# rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "TBD"
eventLocationLink: "https://soundcloud.com/imprint"
eventStreetAddress: ""
eventAddressLocality: "Berlin"
eventAddressLocalityRegion: ""
eventPostalCode: "10115"
eventAddressCountry: "Germany"
eventStartTime: "2016-09-17"
eventDoorTime: "19:00"
# eventEndTime: "2015-09-28T23:00"
# eventPlaceCoordinates: "52.53684, 13.39493"
mapCenterCoordinates: "52.53684, 13.39493"
mapMobileCenterCoordinates: "52.53684, 13.39493"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a partner"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://hackership.us7.list-manage1.com/subscribe/post?u=d893774e9260bf62c4533f5d1&amp;id=d007531236"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets available soon"
ticketsInfo: "<p>Tickets will be available soon. <a href="#subscribe">Sign up for Updates</a>!</p> "
ticketsOffers:
 # -
 #  name: "Presenter"
 #  price: "free"
 #  priceCurrency: ""
 #  ticketsNumber: ""
 #  ribbon: "limited"
 #  buyButtonLink: "/apply/"
 #  buyButtonText: "Apply now"
 #  ticketContentList: ["Apply to present your project to the audience of people interested in contributing."]
 # -
 #  name: "✨ Donation ✨"
 #  price: "10"
 #  priceCurrency: "€"
 #  ticketsNumber: "100"
 #  subtitle: "suggested donation"
 #  ribbon: "top"
 #  featured: true
 #  buyButtonLink: "https://ti.to/opentechschool/opensourcebash-at-wwwtfberlin/"
 #  buyButtonText: "Register now"
 #  ticketContentList: ["We ask that you please donate 10€ to support the OpenTechSchool (non-profit) in running this and other code learning events in Berlin and all over the world."]
 #  validFrom: "2015-09-01T00:00"
 # -
 #  name: "Reserved Seats"
 #  price: "free"
 #  priceCurrency: ""
 #  ticketsNumber: "50"
 #  buyButtonLink: "https://ti.to/opentechschool/opensourcebash-at-wwwtfberlin/"
 #  buyButtonText: "Join Waitlist"
 #  additionalInfo: "Ticket exclusively for people from groups under represented in tech."
 #  ticketContentList: ["Tickets reserved for women and members of groups marginalized in tech."]
 #  validFrom: "2015-09-01T00:00"

# Footer
socialLinks:
 # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=opensourcebash", icon: "twitter"}
 # - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Event Notes"
  links:
   - {link: "/code-of-conduct/", text: "Code of Conduct"}
   - {link: "/accessibility/", text: "accessibility"}
  #  - {link: "http://www.opentechschool.org/berlin", text: "OpenTechSchool Berlin"}
  #  - {link: "https://wwwtf.berlin", text: "wwwtf Berlin"}
 # -
 #  title: "Team Contacts"
 #  links:
 #  #  - {link: "mailto:anouk@opensourcebash.org", text: "Anouk Ruhaak"}
 #  #  - {link: "mailto:ben@opensourcebash.org", text: "Benjamin Kampmann"}
 # -
 #  title: "Information"
 #  links:
 #   - {link: "/code-of-conduct", text: "We operate under a <br/> Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: ""

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Team Block"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
